### ISSUE TITLE
The Map doesn't appear to work.

### ISSUE THREAD

**Issue by markovejnovic** [Everthings/salad.nu#11]
Hello!

I've noticed that the map feature (which is a great idea), doesn't work very well (aka, at all).

I'm willing to work on it, if you need help, when I'm free.

**Comment by Everthings** [comment]
Hey Marko!

Could you go into a bit more detail about the behavior you're seeing? Are you receiving any error messages? Is the map not loading properly (everything is purple)? What browser are you using? etc...

I'm hoping to get a contribution document setup soon, and I'm recruiting a couple contributors to help me build out future versions. There very little documentation right now (working on it!), but if you can find your way around, feel free to submit a PR. Thanks!
